CREATE TABLE public.facility_editors (user_id uuid NOT NULL, hub text NOT NULL CHECK (hub IN ('fr','cz','it','hr','all')), PRIMARY KEY (user_id,hub));
GRANT SELECT ON public.facility_editors TO authenticated;
GRANT ALL ON public.facility_editors TO service_role;
ALTER TABLE public.facility_editors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Editors see own access" ON public.facility_editors FOR SELECT TO authenticated USING (user_id = auth.uid() OR public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'super_admin'));
CREATE POLICY "Admins manage editors" ON public.facility_editors FOR ALL TO authenticated USING (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'super_admin')) WITH CHECK (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'super_admin'));
CREATE FUNCTION public.can_edit_facility(_hub text) RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER SET search_path = public AS $$ SELECT auth.uid() IS NOT NULL AND (public.has_role(auth.uid(),'admin') OR public.has_role(auth.uid(),'super_admin') OR EXISTS (SELECT 1 FROM public.facility_editors WHERE user_id = auth.uid() AND hub IN (_hub,'all'))) $$;
GRANT EXECUTE ON FUNCTION public.can_edit_facility(text) TO authenticated;
CREATE TABLE public.facility_contractors (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), company_name text NOT NULL, contact_name text, phone text, email text, trade text, hub text NOT NULL CHECK (hub IN ('fr','cz','it','hr')), notes text);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.facility_contractors TO authenticated;
GRANT ALL ON public.facility_contractors TO service_role;
ALTER TABLE public.facility_contractors ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Signed in see contractors" ON public.facility_contractors FOR SELECT TO authenticated USING (true);
CREATE POLICY "Editors manage contractors" ON public.facility_contractors FOR ALL TO authenticated USING (public.can_edit_facility(hub)) WITH CHECK (public.can_edit_facility(hub));
CREATE TABLE public.facility_projects (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), title text NOT NULL, hub text NOT NULL CHECK (hub IN ('fr','cz','it','hr')), site text, summary text, owner_id uuid REFERENCES public.ops_team_members(id) ON DELETE SET NULL, co_owner_id uuid REFERENCES public.ops_team_members(id) ON DELETE SET NULL, contractor_id uuid REFERENCES public.facility_contractors(id) ON DELETE SET NULL, status text NOT NULL DEFAULT 'Idea' CHECK (status IN ('Idea','Planned','In progress','On hold','Done','Cancelled')), health text NOT NULL DEFAULT 'On track' CHECK (health IN ('On track','At risk','Off track')), health_note text, priority text NOT NULL DEFAULT 'Medium' CHECK (priority IN ('High','Medium','Low')), start_date date, target_date date, completed_date date, decision_needed boolean NOT NULL DEFAULT false, decision_note text, next_step text, last_reviewed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), CONSTRAINT risk_needs_note CHECK (health = 'On track' OR nullif(trim(health_note),'') IS NOT NULL));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.facility_projects TO authenticated;
GRANT ALL ON public.facility_projects TO service_role;
ALTER TABLE public.facility_projects ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Signed in see projects" ON public.facility_projects FOR SELECT TO authenticated USING (true);
CREATE POLICY "Editors manage projects" ON public.facility_projects FOR ALL TO authenticated USING (public.can_edit_facility(hub)) WITH CHECK (public.can_edit_facility(hub));
CREATE TRIGGER update_facility_projects_updated_at BEFORE UPDATE ON public.facility_projects FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
CREATE TABLE public.facility_milestones (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES public.facility_projects(id) ON DELETE CASCADE, title text NOT NULL, owner_id uuid REFERENCES public.ops_team_members(id) ON DELETE SET NULL, due_date date, done boolean NOT NULL DEFAULT false, done_date date, type text NOT NULL DEFAULT 'Milestone' CHECK (type IN ('Milestone','Deadline','Decision point')), notes text, sort_order integer NOT NULL DEFAULT 0);
GRANT SELECT, INSERT, UPDATE, DELETE ON public.facility_milestones TO authenticated;
GRANT ALL ON public.facility_milestones TO service_role;
ALTER TABLE public.facility_milestones ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Signed in see milestones" ON public.facility_milestones FOR SELECT TO authenticated USING (true);
CREATE POLICY "Editors manage milestones" ON public.facility_milestones FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.facility_projects p WHERE p.id = project_id AND public.can_edit_facility(p.hub))) WITH CHECK (EXISTS (SELECT 1 FROM public.facility_projects p WHERE p.id = project_id AND public.can_edit_facility(p.hub)));
CREATE TABLE public.facility_dependencies (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES public.facility_projects(id) ON DELETE CASCADE, depends_on_project_id uuid REFERENCES public.facility_projects(id) ON DELETE CASCADE, depends_on_milestone_id uuid REFERENCES public.facility_milestones(id) ON DELETE CASCADE, note text, CONSTRAINT one_dependency CHECK ((depends_on_project_id IS NOT NULL) <> (depends_on_milestone_id IS NOT NULL)), CONSTRAINT no_self_dependency CHECK (project_id IS DISTINCT FROM depends_on_project_id));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.facility_dependencies TO authenticated;
GRANT ALL ON public.facility_dependencies TO service_role;
ALTER TABLE public.facility_dependencies ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Signed in see dependencies" ON public.facility_dependencies FOR SELECT TO authenticated USING (true);
CREATE POLICY "Editors manage dependencies" ON public.facility_dependencies FOR ALL TO authenticated USING (EXISTS (SELECT 1 FROM public.facility_projects p WHERE p.id = project_id AND public.can_edit_facility(p.hub))) WITH CHECK (EXISTS (SELECT 1 FROM public.facility_projects p WHERE p.id = project_id AND public.can_edit_facility(p.hub)));
CREATE TABLE public.facility_project_updates (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES public.facility_projects(id) ON DELETE CASCADE, author_id uuid, created_at timestamptz NOT NULL DEFAULT now(), text text NOT NULL, kind text NOT NULL DEFAULT 'Update' CHECK (kind IN ('Update','Decision','Risk','Meeting note')));
GRANT SELECT, INSERT, UPDATE, DELETE ON public.facility_project_updates TO authenticated;
GRANT ALL ON public.facility_project_updates TO service_role;
ALTER TABLE public.facility_project_updates ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Signed in see updates" ON public.facility_project_updates FOR SELECT TO authenticated USING (true);
CREATE POLICY "Editors add updates" ON public.facility_project_updates FOR INSERT TO authenticated WITH CHECK (author_id = auth.uid() AND EXISTS (SELECT 1 FROM public.facility_projects p WHERE p.id = project_id AND public.can_edit_facility(p.hub)));
CREATE TABLE public.facility_project_files (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), project_id uuid NOT NULL REFERENCES public.facility_projects(id) ON DELETE CASCADE, file_path text NOT NULL, label text NOT NULL, uploaded_by uuid, created_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.facility_project_files TO authenticated;
GRANT ALL ON public.facility_project_files TO service_role;
ALTER TABLE public.facility_project_files ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Signed in see project files" ON public.facility_project_files FOR SELECT TO authenticated USING (true);
CREATE POLICY "Editors add project files" ON public.facility_project_files FOR INSERT TO authenticated WITH CHECK (uploaded_by = auth.uid() AND EXISTS (SELECT 1 FROM public.facility_projects p WHERE p.id = project_id AND public.can_edit_facility(p.hub)));
CREATE TABLE public.facility_weekly_notes (week_start date PRIMARY KEY, text text NOT NULL DEFAULT '', author uuid, updated_at timestamptz NOT NULL DEFAULT now());
GRANT SELECT, INSERT, UPDATE, DELETE ON public.facility_weekly_notes TO authenticated;
GRANT ALL ON public.facility_weekly_notes TO service_role;
ALTER TABLE public.facility_weekly_notes ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Signed in see weekly notes" ON public.facility_weekly_notes FOR SELECT TO authenticated USING (true);
CREATE POLICY "Editors manage weekly notes" ON public.facility_weekly_notes FOR ALL TO authenticated USING (public.can_edit_facility('all')) WITH CHECK (public.can_edit_facility('all'));
ALTER TABLE public.ops_tasks ADD COLUMN project_id uuid REFERENCES public.facility_projects(id) ON DELETE SET NULL;
CREATE INDEX facility_milestones_project_idx ON public.facility_milestones(project_id);
CREATE INDEX facility_projects_hub_idx ON public.facility_projects(hub);
CREATE INDEX ops_tasks_project_idx ON public.ops_tasks(project_id);